/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


typedef unsigned int uint32_t;

//RCC
#define RCC_BASE          0x40021000
#define RCC_APB2ENR       *(volatile unsigned int *)(RCC_BASE + 0x18)  //bit 2 set
#define RCC_CR		*(volatile uint32_t *)(RCC_BASE+0x00)//Clock control register
#define HSION	(1UL<<0)

//GPIO
#define GPIOA_BASE         0x40010800
#define GPIOA_CRH          *(volatile unsigned int *)(GPIOA_BASE + 0x18)
#define GPIOA_ODR          *(volatile unsigned int *)(GPIOA_BASE + 0x0C)
#define GPIOA_CRL          *(volatile unsigned int *)(GPIOA_BASE + 0x00)

//EXTI
#define EXTI_BASE         0x40010400
#define EXTI_IMR          *(volatile unsigned int *)(EXTI_BASE + 0x00 )
#define EXTI_RTSR         *(volatile unsigned int *)(EXTI_BASE + 0x08 )
#define EXTI_PR           *(volatile unsigned int *)(EXTI_BASE + 0x14 )

//AFIO
#define AFIO_BASE         0x40010000
#define AFIO_EXTICR1      *(volatile unsigned int *)(AFIO_BASE + 0x08 )

//NVIC from data sheet of cortexm3
#define NVIC_EXTIE0       *(volatile unsigned int *)(0xE000E100)

void clock_init()
{
	//	Bit 0 HSION: Internal high-speed clock enable
	//	RCC_CR 		|=HSION;
	//enable clock GPIO
	RCC_APB2ENR |=(1<<2);

	//enable clock AFIO
	RCC_APB2ENR |=(1<<0);

}

void GPIO_init()
{

	//make pin13 portA output
	GPIOA_CRH &=0xFF0FFFFF ;
	GPIOA_CRH |=0x00200000 ;

	//make pin0 portA Floating input (reset state)
	GPIOA_CRL |= (1<<2);
}



int main(void)
{
	 clock_init();
	 GPIO_init();
	//enable EXTI0 to portA0
	AFIO_EXTICR1 =0;

	//enable mask register and rising edge register
	EXTI_IMR |=(0<<0) ;
	EXTI_RTSR |=(1<<0);

	//enable NVIC Irq6 EXTI0
	NVIC_EXTIE0 |=(1<<6);

    /* Loop forever */
	for(;;);
}


void EXTI0_IRQHandler()
{
	//IRQ is happened from portA pin 13  ,,rising edge
	//toggle pin13 portA
	GPIOA_ODR ^= (1<<13);

	//clear the pending request
	EXTI_PR |=(1<<0);
}













