/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "core_cm3.h"

#include "stm32_f103c6_drivers_GPIO.h"
#include "stm32_f103x6.h"
#include "stm32_f103c6_drivers_EXTI.h"
#include "stm32_f103c6_drivers_USART.h"





//arm lesson 5///////////////////////////////////////////////////////////////////////////////////////
extern _estack;

#define TaskA_stack_size  100
#define TaskB_stack_size  100

#define OS_Set_PSP(add)             __asm volatile("MOV r0,%0 \n\t MSR PSP,r0" : :"r" (add))
#define OS_Switch_SP_to_PSP 		__asm volatile("MRS r0,CONTROL \n\t MOV r1,#0x02 \n\t ORR r0,r0,r1 \n\t MSR CONTROL, r0")
#define OS_Switch_SP_to_MSP 		__asm volatile("MRS r0,CONTROL \n\t MOV r1,#0x05 \n\t AND r0,r0,r1 \n\t MSR CONTROL, r0")
#define OS_Generate_Exception       __asm volatile("SVC #0x3")

//main stack
unsigned int _S_MSP = &_estack;
unsigned int _E_MSP ;

//TaskA stack
unsigned int _S_PSP_TA;
unsigned int _E_PSP_TA;

//TaskA stack
unsigned int _S_PSP_TB;
unsigned int _E_PSP_TB;


int volatile IRQ_Flag;
int volatile TaskA_Falg;
int volatile TaskB_Falg;


int IPSR_out;
enum CPU_AccessLevel{privileged, unprivileged};
void Switch_CPU_AccessLevel(enum CPU_AccessLevel level)
{
	switch(level){
	case privileged:         //clear bit0 in CONTROL register
		__asm("MRS r3,CONTROL \n\t"
				"LSR r3,r3,#0x1 \n\t"
				"LSL r3,r3,#0x1  \n\t"
				"MSR CONTROL, r3");
		break;

	case unprivileged:           //set bit0 in CONTROL register
		__asm("MRS r3,CONTROL \n\t"
				"ORR r3,r3,#0x1 \n\t"
				"MSR CONTROL,r3");
		break;
	}
}
void HardFault_Handler()
{
	Switch_CPU_AccessLevel(privileged);
}

void EXTI9_callBack(void)
{	if(IRQ_Flag ==0)
	{
		TaskA_Falg ==1;
		IRQ_Flag ==1;
	}else if(IRQ_Flag ==1)
	{
		TaskB_Falg == 1;
		IRQ_Flag == 0 ;
	}

	Switch_CPU_AccessLevel(privileged);
	__asm("MRS r4,IPSR"
	);
	__asm("MOV %0,r4"
			: "=r" (IPSR_out));
	IRQ_Flag = 1;
}

void SVC_Handler(){
	Switch_CPU_AccessLevel(privileged);
}
int TaskA(int a,int b,int c)
{
	return (a+b+c);
}

int TaskB(int a,int b,int c,int d)
{
	return (a+b+c+d);
}

void MainOs()
{
	//main stack
	_E_MSP = (_S_MSP -512);

	//TaskA PSP
	_S_PSP_TA = (_E_MSP - 8);
	_E_PSP_TA =(_S_PSP_TA - 100 );

	//TaskB PSP
	_S_PSP_TB = (_E_PSP_TA - 8);
	_E_PSP_TB =(_S_PSP_TB - 100 );

	while(1)
	{
		__asm("NOP");
		if(TaskA_Falg ==1)
		{
			//set PSP register = _S_PSP_TA
			OS_Set_PSP(_S_PSP_TA);
			// SP -> PSP
			OS_Switch_SP_to_PSP;
			//switch from privileged to unprivileged
			Switch_CPU_AccessLevel(unprivileged);

			TaskA_Falg =TaskA(1, 2, 3);

			//switch from unprivileged to privileged
			OS_Generate_Exception;
			// SP -> MSP
			OS_Switch_SP_to_MSP;

		}else if(TaskB_Falg==1)
		{
			//set PSP register = _S_PSP_TB
			OS_Set_PSP(_S_PSP_TB);
			// SP -> PSP
			OS_Switch_SP_to_PSP;
			//switch from privileged to unprivileged
			Switch_CPU_AccessLevel(unprivileged);

			TaskB_Falg =TaskB(1, 2, 3, 4);

			//switch from unprivileged to privileged
			OS_Generate_Exception;
			// SP -> MSP
			OS_Switch_SP_to_MSP;
		}
	}
}


int main()
{

	//enable clocks
	RCC_GPIOB_CLK_EN();
	RCC_GPIOA_CLK_EN();
	AFIO_CLK_EN();

	//Switch_CPU_AccessLevel(unprivileged);

	EXTI_PinConfig_t EXTI_CFG;
	EXTI_CFG.EXTI_PIN = EXTI9PB9;
	EXTI_CFG.trigger_Case = EXTI_trigger_rising ;
	EXTI_CFG.P_IRQ_CallBack = EXTI9_callBack;
	EXTI_CFG.IQR_ENB = EXTI_IRQ_enable;
	Mcal_EXTI_GPIO_init(&EXTI_CFG);

	MainOs();
	IRQ_Flag =1;
	while(1)
	{
		if(IRQ_Flag)
		{

			IRQ_Flag=0;
		}
	}

	return 0;
}








