/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif





#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>


//RCC
#define RCC_BASE          0x40021000
#define RCC_APB2ENR       *(volatile unsigned int *)(RCC_BASE + 0x18)  //bit 2 set
#define RCC_CR		      *(volatile unsigned int *)(RCC_BASE+0x00)//Clock control register
#define RCC_IOPAEN        (1<<2)
#define RCC_IOPBEN        (1<<3)

//GPIO
#define GPIOA_BASE         0x40010800
#define GPIOA_CRH          *(volatile unsigned int *)(GPIOA_BASE + 0x04)
#define GPIOA_CRL          *(volatile unsigned int *)(GPIOA_BASE + 0x00)
#define GPIOA_ODR          *(volatile unsigned int *)(GPIOA_BASE + 0x0C)
#define GPIOA_IDR          *(volatile unsigned int *)(GPIOA_BASE + 0x08)


#define GPIOB_BASE         0x40010C00
#define GPIOB_CRH          *(volatile unsigned int *)(GPIOB_BASE + 0x04)
#define GPIOB_CRL          *(volatile unsigned int *)(GPIOB_BASE + 0x00)
#define GPIOB_ODR          *(volatile unsigned int *)(GPIOB_BASE + 0x0C)
#define GPIOB_IDR          *(volatile unsigned int *)(GPIOB_BASE + 0x08)


void clock_init()
{

	//enable clock GPIOA
	RCC_APB2ENR |=RCC_IOPAEN;

	//enable clock GPIOB
	RCC_APB2ENR |=RCC_IOPBEN;

}

void GPIO_init()
{
	GPIOA_CRL  =0;
	GPIOA_CRH  =0;
	GPIOB_CRL =0;
	GPIOB_CRH =0;

	//PA1 input HZ
	GPIOA_CRL |= (1<<6);

	//PB1 output push pull
	//Output mode, max speed 10 MHz.   CNF:00
	GPIOB_CRL |=(1<<4);

	//PA13 input HZ
	GPIOA_CRH |=(1<<22);


	//PB13 output push pull
	// Output mode, max speed 10 MHz.  CNF:00
	GPIOB_CRH |=(1<<20);
}

void wait_ms(int time)
{
	unsigned int i,j;
	for(i=0; i<time; i++)
	{
		for(j=0; j<255; j++);
	}
}


int main(void)
{
	 clock_init();
	 GPIO_init();

	 while(1)
	 {
		 if(((GPIOA_IDR & (1<<1)) >>1) == 0)      //single press
		 {
			 GPIOB_ODR ^= (1<<1);
			 while((((GPIOA_IDR & (1<<1)) >>1) == 0));
		 }



		 if(((GPIOA_IDR & (1<<13)) >>13) == 1) //multi press
		 		 {
		 			 GPIOB_ODR ^= (1<<13);
		 		 }
		 wait_ms(1);

	 }



}




