/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "GPIO_Interface.h"
#include "NVIC.h"
#include "LCD.h"
#include "SYSTICK.h"
#include "KeyPad.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


static int count_OV=0;
char key=0;
int seconds=10;
int minutes=15;

void Display(int r,int c){
	LCD_GoTo(r,c);
	if(c == 3 && seconds < 10){
		LCD_writeNumber(0);
		LCD_writeNumber(seconds);
	}else if(c == 3 && seconds >= 10){
		LCD_writeNumber(seconds);
	}else if(c == 0 && minutes < 10){
		LCD_writeNumber(0);
		LCD_writeNumber(minutes);
	}else if(c == 0 && minutes >= 10){
		LCD_writeNumber(minutes);
	}
	for(int i=0;i<50;i++);
}
void SystickCALLB()
{
	count_OV++;
	if(count_OV % 1 ==0){
		seconds--;
		Display(0,3);
	}
	if(seconds == 0){
		minutes--;
		seconds=59;
		LCD_Clear();
		Display(0,0);
	}
}

int main(void)
{
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	LCD_Init();

	Keypad_Init();

	GPIO_PinConfig_t* pinconf={0};
	pinconf->GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	pinconf->GPIO_OUTPUT_SPEED = GPIO_SPEED_10M;
	pinconf->GPIO_PinNumber = GPIO_PIN_7;
	MCAL_GPIO_Init(GPIOB, pinconf);

	SYSTICK_Init();
	SYSTICK_SetTime(1000000,8);
	SYSTICK_SetCallback(SystickCALLB);
	SYSTICK_Start();

	char* buffer=0;
	LCD_writeNumber(minutes);
	LCD_SendChar(':');
	LCD_writeNumber(seconds);
	for(int i=0;i<100;i++);
	int tens=1,ones=1;
	int tens_min=1,ones_min=1;
	Display(0,0);
	//Display();


	/* Loop forever */
	while(1){
		key= Keypad_GetKey(buffer);
		if (key =='A')
		{
			LCD_GoTo(0, 0);
			while(1){
				key = Keypad_GetKey(buffer);
				if(key >= '0' && key <= '9'){
					tens_min = key-48;
					break;
				}
			}
			LCD_SendChar(key);
			LCD_GoTo(0, 1);
			while(1){
				key = Keypad_GetKey(buffer);
				if(key >= '0' && key <= '9'){
					ones_min = key-48;
					break;
				}
			}
			LCD_SendChar(key);  //dfghjk
			if((tens_min*10 + ones_min) <60){
				minutes = tens_min*10 + ones_min;
				//LCD_Clear();
				Display(0,0);
			}
		}

		if (key == 'B')
		{
			while(1){
				key = Keypad_GetKey(buffer);
				if(key >= '0' && key <= '9'){
					tens = key-48;
					break;
				}
			}
			while(1){
				key = Keypad_GetKey(buffer);
				if(key >= '0' && key <= '9'){
					ones = key-48;
					//while(Keypad_GetKey(buffer) != '/0');
					break;
				}
			}
			if((tens*10 + ones) <60){
				seconds = tens*10 + ones;
				Display(0,1); //dfghj
			}

		}
		//for(int i=0;i<1000;i++);
	}
}




























///task2
//
//static int count_OV=0;
//void SystickCALLB()
//{
//	count_OV++;
//	MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_7);
//
//	if(count_OV % 5 ==0){LCD_SendString("G6:");}
//
//	if(count_OV % 10 ==0){LCD_SendString("free palastine");}
//
//	for(int i=0;i<100000;i++);
//	LCD_Clear();
//
//}
//
//int main(void)
//{
//	RCC_GPIOA_CLK_EN();
//	RCC_GPIOB_CLK_EN();
//	LCD_Init();
//
//	GPIO_PinConfig_t* pinconf;
//	pinconf->GPIO_MODE = GPIO_MODE_OUTPUT_PP;
//	pinconf->GPIO_OUTPUT_SPEED = GPIO_SPEED_10M;
//	pinconf->GPIO_PinNumber = GPIO_PIN_7;
//	MCAL_GPIO_Init(GPIOB, pinconf);
//
//	SYSTICK_Init();
//	SYSTICK_SetTime(1000000,8);
//	SYSTICK_SetCallback(SystickCALLB);
//	SYSTICK_Start();
//
//	/* Loop forever */
//	for(;;);
//}
