/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "core_cm3.h"

#include "stm32_f103c6_drivers_GPIO.h"
#include "stm32_f103x6.h"
#include "stm32_f103c6_drivers_EXTI.h"
#include "stm32_f103c6_drivers_USART.h"





//ARM Lesson7 final lab2 & lab3

int volatile IRQ_Flag;
int IPSR_out;

void PendSV_Handler(){

}
void OS_SVC(int* stack_frame)
{
	//r0,r1,r2,r3,r12,LR,PC,XPSR
	unsigned char SVC_number;
	unsigned int val1,val2;
	val1 = stack_frame[0];
	val2 =stack_frame[1];
	SVC_number = *((unsigned char*)(((unsigned char*)stack_frame[6])-2));

	switch(SVC_number)
	{
	case 0:
		stack_frame[0]= val1 + val2;
		break;
	case 1:
		stack_frame[0]= val1 - val2;
		break;
	case 2:
		stack_frame[0]= val1 * val2;
		break;
	case 3:
		SCB->ICSR |= SCB_ICSR_PENDSVSET_Msk;
		break;
	}
}

__attribute((naked)) void SVC_Handler()
{
	__asm("TST LR,#4 \n\t"
			"ITE EQ \n\t"
			"mrseq R0,MSP \n\t"
			"mrsne R0,PSP \n\t"
			"B OS_SVC");

}

int OS_SVC_Set(int a,int b, int SVC_ID)
{
	int return_val;
	switch(SVC_ID)
	{
	case 0:
		__asm("SVC #0x00");
		break;
	case 1:
		__asm("SVC #0x01");
		break;
	case 2:
		__asm("SVC #0x02");
		break;
	case 3:
		__asm("SVC #0x03");
		break;
	}

	__asm("MOV %0,R0":"=r"(return_val));
	return return_val;
}

int main()
{

	//enable clocks
	RCC_GPIOB_CLK_EN();
	RCC_GPIOA_CLK_EN();
	AFIO_CLK_EN();

	int result;
	result = OS_SVC_Set(3,3, 0);
	result = OS_SVC_Set(3,3, 1);
	result = OS_SVC_Set(3,3, 2);
	OS_SVC_Set(3,3, 3);
	IRQ_Flag =1;
	while(1)
	{
		if(IRQ_Flag)
		{

			IRQ_Flag=0;
		}
	}

	return 0;
}




